server:
  port: 9050
spring:
  datasource:
    url: ${db.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.username}
    password: ${db.password}
    hikari:
      maximum-pool-size: 15        # 根据应用负载调整
      minimum-idle: 15             # 与最大值相同
      idle-timeout: 300000         # 5分钟
      max-lifetime: 1800000        # 30分钟（建议比数据库超时短）
      connection-timeout: 30000    # 30秒（获取连接超时时间）
      leak-detection-threshold: 300000  # 5分钟（检测连接泄漏）
      validation-timeout: 5000     # 5秒（连接验证超时）
  servlet:
    multipart:
      max-file-size: 100MB      # 单个文件的最大大小
      max-request-size: 100MB   # 单个请求的最大大小（包含所有文件）
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
fileserver:
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: waxberry
auth:
  ALIBABA_CLOUD_ACCESS_KEY_ID: 
  ALIBABA_CLOUD_ACCESS_KEY_SECRET: 
  issuerUrl: http://localhost
  privateKey: 


