CREATE TABLE mgr_agent_agent (
  id                   VARCHAR(100) NOT NULL COMMENT '主键',
  name                 VARCHAR(100) DEFAULT '' COMMENT 'agent名称',
  agent_label          VARCHAR(100) DEFAULT '' COMMENT 'agent标签,以逗号隔开储存',
  discription          TEXT COMMENT 'agent介绍',
  status               INT DEFAULT 0  COMMENT 'agent状态,0未发布,1发布',
  creator_id            VARCHAR(100) DEFAULT '' COMMENT 'agent创建人',
  create_time          DATETIME COMMENT 'agent创建时间',
  update_time          DATETIME COMMENT 'agent更新时间',
  classification_id    VARCHAR(100) DEFAULT ''  COMMENT 'agent的文件夹ID',
  sort_order           INT DEFAULT 0  COMMENT 'agent排序',
  ismodify             INT DEFAULT 0  COMMENT '是否可以修改 0表示可以 1表示不可以',
  file_id              VARCHAR(100) DEFAULT '' COMMENT '附件Id',
  file_name            VARCHAR(100) DEFAULT '' COMMENT '附件名称',
  group_id             VARCHAR(100) DEFAULT '' COMMENT '市场分类ID',
  imge_file_id         VARCHAR(100) DEFAULT '' COMMENT '图片文件ID',
  vessel_id            VARCHAR(100) DEFAULT '' COMMENT '容器ID',
  cover_file_id        VARCHAR(100) DEFAULT '' COMMENT '封面文件ID',
  vessel_port          INT DEFAULT 0  COMMENT '容器端口',
  type                 INT DEFAULT 0  COMMENT '类型',
  step                 VARCHAR(20) COMMENT '步骤',
  is_copy              INT DEFAULT 0  COMMENT '是否复制',
  PRIMARY KEY (id)
)ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;