CREATE TABLE IF NOT EXISTS oauth2_authorization (
    id varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
    registered_client_id varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
    principal_name varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
    authorization_grant_type varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
    authorized_scopes varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    attributes blob,
    state varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    authorization_code_value blob,
    authorization_code_issued_at timestamp NULL DEFAULT NULL,
    authorization_code_expires_at timestamp NULL DEFAULT NULL,
    authorization_code_metadata blob,
    access_token_value blob,
    access_token_issued_at timestamp NULL DEFAULT NULL,
    access_token_expires_at timestamp NULL DEFAULT NULL,
    access_token_metadata blob,
    access_token_type varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    access_token_scopes varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    oidc_id_token_value blob,
    oidc_id_token_issued_at timestamp NULL DEFAULT NULL,
    oidc_id_token_expires_at timestamp NULL DEFAULT NULL,
    oidc_id_token_metadata blob,
    refresh_token_value blob,
    refresh_token_issued_at timestamp NULL DEFAULT NULL,
    refresh_token_expires_at timestamp NULL DEFAULT NULL,
    refresh_token_metadata blob,
    user_code_value blob,
    user_code_issued_at timestamp NULL DEFAULT NULL,
    user_code_expires_at timestamp NULL DEFAULT NULL,
    user_code_metadata blob,
    device_code_value blob,
    device_code_issued_at timestamp NULL DEFAULT NULL,
    device_code_expires_at timestamp NULL DEFAULT NULL,
    device_code_metadata blob,
    PRIMARY KEY (id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;